//
// Created by Ethan on 2022/06/03.
//

#ifndef ELEMENTALCOGNITIONSYSTEM_BASEUNIT_H
#define ELEMENTALCOGNITIONSYSTEM_BASEUNIT_H

// 基准单元
class BaseUnit {
public:
};


#endif //ELEMENTALCOGNITIONSYSTEM_BASEUNIT_H
