//
// Created by Ethan on 2022/06/03.
//

#ifndef ELEMENTALCOGNITIONSYSTEM_GATEUNIT_H
#define ELEMENTALCOGNITIONSYSTEM_GATEUNIT_H

/// 门单元，作为各单元之基本连接。
class GateUnit {

};


#endif //ELEMENTALCOGNITIONSYSTEM_GATEUNIT_H
